[package]
name = "gist-i"
version = "0.1.0"
authors = ["Gwen Lofman <Gwen@Lofman.io>"]
description = "A utility for pretty-printing git stats"
license = "MPL-2.0"
readme = "README.md"
repository = "https://github.com/glfmn/gist"
keywords = ["DSL", "git", "gist", "status", "pretty-printing"]
exclude = [
    img/*.gif
]

[dependencies]
ansi_term = "0.9"
git2 = "0.6.10"
clap = "~2.29"
nom = "^3.2"
rand = "0.3"
rand_derive = "0.3"

[dev-dependencies]
quickcheck = "0.4"
