[package]
name = "gist"
version = "0.1.0"
authors = ["Gwen Lofman <Gwen@Lofman.io>"]
description = "A utility for pretty-printing git stats"
license = "MPL-2.0"
readme = "README.md"


[dependencies]
git2 = "0.6"
docopt = "0.8"
serde = "1.0"
serde_derive = "1.0"
