[package]
name = "glitter-lang"
version = "0.1.3"
authors = ["Gwen Lofman <Gwen@Lofman.io>"]

[dependencies]
ansi_term = "0.11"
git2 = "0.7.1"
nom = "^3.2"

[dev-dependencies]
proptest = "0.8.6"
criterion = "0.2"

[[bench]]
name = "interpreter"
harness = false
